#!/usr/bin/env python3

import sys
import os

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QIcon

from widgets.player import PlayerWindow


def set_rosdistro(ros_distro):
    ui_player.set_rosdistro(ros_distro)


def set_rospath(ros_path):
    ui_player.set_rospath(ros_path)


if __name__ == '__main__':
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

    rosbag = ''
    try:
        rosbag = sys.argv[1]
        print("[INFO] app start with rosbag", rosbag)
    except:
        print("[INFO] app start")

    app = QApplication(sys.argv)
    with open(SCRIPT_DIR + '/ui/stylesheet.css', 'r') as f:
        style = f.read()
        app.setStyleSheet(style)

    ui_player = PlayerWindow(SCRIPT_DIR + '/ui/player.ui', SCRIPT_DIR + '/config/player.conf')
    ui_player.setWindowIcon(QIcon(SCRIPT_DIR + '/img/rosbag_player.png'))
    ui_player.show()

    if rosbag != '':
        ui_player.set_rosbag(rosbag)
        
    sys.exit(app.exec())
