#!/usr/bin/env python3

import sys
import os

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QIcon

from widgets.player import PlayerWindow

if __name__ == '__main__':
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

    rosbag = ''
    try:
        rosbag = sys.argv[1]
        print("[INFO] app start with rosbag", rosbag)
    except:
        print("[INFO] app start")

    app = QApplication(sys.argv)
    with open(SCRIPT_DIR + '/ui/stylesheet.css', 'r') as f:
        style = f.read()
        app.setStyleSheet(style)

    path_conf_file = SCRIPT_DIR + '/path.conf'
    if not os.path.exists(path_conf_file):
        with open(path_conf_file, 'w') as f:
            f.write('/opt/ros/humble/setup.bash')
    
    ws_paths = []
    with open(path_conf_file, 'r') as f:
        for path in f.readlines():
            ws_paths.append(path.strip())

    ui_player = PlayerWindow(SCRIPT_DIR + '/ui/player.ui', SCRIPT_DIR + '/config/player.conf', ws_paths)
    ui_player.setWindowIcon(QIcon(SCRIPT_DIR + '/img/rosbag_player.png'))
    ui_player.show()

    if rosbag != '':
        ui_player.set_rosbag(rosbag)
        
    sys.exit(app.exec())
